
project_id = "kaebtzbmtozoqvsdojkl"

[api]
enabled = true
# Uncomment the next line to use our custom email verification function
email_confirm_url = "https://kaebtzbmtozoqvsdojkl.supabase.co/functions/v1/custom-email-verification"

[functions.custom-email-verification]
verify_jwt = false
